---
- name: Instalacion de paquetes base
  hosts: webservers
  become: true

  tasks:
    - name: Instalar herramientas de administración
      ansible.builtin.dnf:
        name:
          - htop
          - tmux
          - nmap
        state: present